#ifndef TYPES_H
#define TYPES_H

//GAME
#define BOARD_SIZE 40
#define MAX_PLAYERS 4
#define MAX_ROUNDS 500
#define EVENT_CARDS 20
#define STARTING_CASH 30000

//FINANCIAL
#define GO_REWARD 2000
#define BAIL 300
#define MI_BID_INCREMENT 250
#define MAX_LOAN_PERCENTAGE 75
#define LOAN_DURATION 20
#define INSURANCE_DURAION 20
#define AUCTION_OPENING_PERCENTAGE 5

//EVENT INTERVALS - ROUNDS
#define INFLATION_INTERVAL 10
#define MARKET_REVIEW_INTERVAL 10
#define DISASTER_INTERVAL 10
#define NATIONAL_EVENT_INTERVAL 15
#define REGIONAL_EVENT_INTERVAL 15
#define REGULATION_DURATION 20

//INFLATION RATES PERCENTAGE
#define INFLATION_RATES_COUNT 6
#define DEFLATION_RATE_3 -3
#define INFLATION_RATE_0 0
#define INFLATION_RATE_2 2
#define INFLATION_RATE_5 5
#define INFLATION_RATE_8 8
#define INFLATION_RATE_12 12

//GOVERNMENT REGULATION MODIFIERS
#define REGULATION_INCOME_TAX_MODIFIER 50


//BUILDING CONDITION PERCENTAGES
#define CONDITION_DROP_PER_ROUND 2
#define MIN_CONDITION_FOR_RENT 5
#define MAX_CONDITION 100

//MAINTENANCE
#define HOUSE_MAINTENANCE_PERCENTAGE 5
#define HOTEL_MAINTENANCE_PERCENTAGE 8
#define RENOVATION_COST_PERCENTAGE 25

//DEPRECIATION
#define DEPRECIATION_START_AGE 50
#define DEPRECIATION_RATE 1
#define DEPRECIATION_INTERVAL 5
#define MAX_DEPRECIATION 30

//STRUCTURAL DAMAGE
#define STRUCTURAL_DAMAGE_PROPERTY_VALUE_REDUCTION 15
#define STRUCTURAL_DAMAGE_RENT_REDUCTION 25
#define STRUCTURAL_DAMAGE_MAINTENANCE_INCREASE 5

//INSURANCE PREMIUM
#define BASIC_INSURANCE_PREMIUM 5
#define COMPREHENSIVE_INSURANCE_PREMIUM 1
#define BUSINESS_INSURANCE_PREMIUM 15

//RENT
#define RENT_1_HOUSE 2 //MULTIPLIER * BASE RENT
#define RENT_2_HOUSE 3
#define RENT_3_HOUSE 5
#define RENT_4_HOUSE 7
#define RENT_HOTEL 10

#define RAILWAY_1 250 //LKR
#define RAILWAY_2 500
#define RAILWAY_3 1000
#define RAILWAY_4 2000

#define UTILITY_1 4 //MULTIPLIER * DICE VALUE
#define UTILITY_2 10

//ANTI-SPECULATION
#define ANTI_SPECULATION_MAX_UNDEVELOPED 3
#define ANTI_SPECULATION_DEADLINE 5

//STRING LENGTH
#define PROPERTY_NAME_LEN 50
#define PLAYER_NAME_LEN 50